#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : onnx
Version  : 1.6.0
Release  : 23
URL      : https://files.pythonhosted.org/packages/81/a9/a14c3bc32908c37b46b19a89eb6185b0c90fd9c03ef12379d51940b8fc71/onnx-1.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/81/a9/a14c3bc32908c37b46b19a89eb6185b0c90fd9c03ef12379d51940b8fc71/onnx-1.6.0.tar.gz
Summary  : Open Neural Network Exchange
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: onnx-bin = %{version}-%{release}
Requires: onnx-license = %{version}-%{release}
Requires: onnx-python = %{version}-%{release}
Requires: onnx-python3 = %{version}-%{release}
Requires: numpy
Requires: protobuf
Requires: six
Requires: typing_extensions
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : dos2unix
BuildRequires : nbval
BuildRequires : numpy
BuildRequires : protobuf
BuildRequires : protobuf-dev
BuildRequires : pybind11-dev
BuildRequires : pytest
BuildRequires : pytest-runner
BuildRequires : python-tabulate
BuildRequires : python3-dev
BuildRequires : six
BuildRequires : typing_extensions
Patch1: fix-build.patch

%description
![pybind11 logo](https://github.com/pybind/pybind11/raw/master/docs/pybind11-logo.png)

%package bin
Summary: bin components for the onnx package.
Group: Binaries
Requires: onnx-license = %{version}-%{release}

%description bin
bin components for the onnx package.


%package license
Summary: license components for the onnx package.
Group: Default

%description license
license components for the onnx package.


%package python
Summary: python components for the onnx package.
Group: Default
Requires: onnx-python3 = %{version}-%{release}

%description python
python components for the onnx package.


%package python3
Summary: python3 components for the onnx package.
Group: Default
Requires: python3-core

%description python3
python3 components for the onnx package.


%prep
%setup -q -n onnx-1.6.0
cd %{_builddir}/onnx-1.6.0
%patch1 -p1

%build
## build_prepend content
find | xargs  -n 1 dos2unix
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588360962
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pyver=$(pkg-config --modversion python3)
export PYTHONPATH="$PWD/build/lib.linux-x86_64-$pyver"
pytest -v
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/onnx
cp %{_builddir}/onnx-1.6.0/LICENSE %{buildroot}/usr/share/package-licenses/onnx/72abeb57e64fb30074f90a0cf3238a35f63d8a6d
cp %{_builddir}/onnx-1.6.0/third_party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/onnx/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/onnx-1.6.0/third_party/pybind11/LICENSE %{buildroot}/usr/share/package-licenses/onnx/a33b61f04391a38904373d020e7fbabf211383f6
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/backend-test-tools
/usr/bin/check-model
/usr/bin/check-node

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/onnx/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/onnx/72abeb57e64fb30074f90a0cf3238a35f63d8a6d
/usr/share/package-licenses/onnx/a33b61f04391a38904373d020e7fbabf211383f6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
