#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-onnx
Version  : 1.14.1
Release  : 67
URL      : https://files.pythonhosted.org/packages/8f/71/1543d8dad6a26df1da8953653ebdbedacea9f1a5bcd023fe10f8c5f66d63/onnx-1.14.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/8f/71/1543d8dad6a26df1da8953653ebdbedacea9f1a5bcd023fe10f8c5f66d63/onnx-1.14.1.tar.gz
Summary  : Open Neural Network Exchange
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: pypi-onnx-bin = %{version}-%{release}
Requires: pypi-onnx-license = %{version}-%{release}
Requires: pypi-onnx-python = %{version}-%{release}
Requires: pypi-onnx-python3 = %{version}-%{release}
Requires: pypi(typing_extensions)
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : dos2unix
BuildRequires : protobuf-c-dev
BuildRequires : protobuf-dev
BuildRequires : pypi(numpy)
BuildRequires : pypi(protobuf)
BuildRequires : pypi(pytest_runner)
BuildRequires : pypi(typing_extensions)
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Open Neural Network Exchange (ONNX) is an open ecosystem that empowers AI
developers to choose the right tools as their project evolves. ONNX provides an
open source format for AI models, both deep learning and traditional ML. It
defines an extensible computation graph model, as well as definitions of
built-in operators and standard data types. Currently we focus on the
capabilities needed for inferencing (scoring).

%package bin
Summary: bin components for the pypi-onnx package.
Group: Binaries
Requires: pypi-onnx-license = %{version}-%{release}

%description bin
bin components for the pypi-onnx package.


%package license
Summary: license components for the pypi-onnx package.
Group: Default

%description license
license components for the pypi-onnx package.


%package python
Summary: python components for the pypi-onnx package.
Group: Default
Requires: pypi-onnx-python3 = %{version}-%{release}

%description python
python components for the pypi-onnx package.


%package python3
Summary: python3 components for the pypi-onnx package.
Group: Default
Requires: python3-core
Provides: pypi(onnx)
Requires: pypi(numpy)
Requires: pypi(protobuf)
Requires: pypi(typing_extensions)

%description python3
python3 components for the pypi-onnx package.


%prep
%setup -q -n onnx-1.14.1
cd %{_builddir}/onnx-1.14.1
pushd ..
cp -a onnx-1.14.1 buildavx2
popd

%build
## build_prepend content
find | xargs -n 1 dos2unix
# requires an additional archive to run these tests... avoid for now
#export ONNX_BUILD_TESTS=1
export CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX=/usr"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695164135
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . protobuf
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
## build_prepend content
find | xargs -n 1 dos2unix
# requires an additional archive to run these tests... avoid for now
#export ONNX_BUILD_TESTS=1
export CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX=/usr"
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pypi-dep-fix.py . protobuf
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-onnx
cp %{_builddir}/onnx-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-onnx/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/onnx-%{version}/third_party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/pypi-onnx/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/onnx-%{version}/third_party/pybind11/LICENSE %{buildroot}/usr/share/package-licenses/pypi-onnx/3dbd61e2b2c71dcc658c3da90bacf2e15958075a || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
pypi-dep-fix.py %{buildroot} protobuf
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/backend-test-tools
/usr/bin/check-model
/usr/bin/check-node

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-onnx/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-onnx/3dbd61e2b2c71dcc658c3da90bacf2e15958075a

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
